name: ciudad_rio_app
description: App de acceso Ciudad del Rio â€” QR para empleados
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.6

  # QR
  qr_flutter: ^4.1.0
  crypto: ^3.0.3

  # UI y utilidades
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
